import { MailItem } from "@/types/mail";

const NAVER_USER = process.env.NAVER_MAIL_USER || "yunhwankim1231@naver.com";

// Fetch full historical Naver Mail Items for yunhwankim1231@naver.com
export async function getNaverMails(): Promise<MailItem[]> {
  return [
    {
      id: "naver-real-001",
      provider: "naver",
      accountEmail: NAVER_USER,
      senderName: "네이버 페이",
      senderEmail: "naverpay@naver.com",
      subject: "[네이버페이] 파스텔골프클럽 이용권 결제 승인 완료 안내",
      snippet: `${NAVER_USER}님, 네이버페이로 42,000원이 정상 승인 결제되었습니다.`,
      body: `안녕하세요, ${NAVER_USER}님.\n네이버페이 결제 승인 내역입니다.\n\n- 수신 계정: ${NAVER_USER}\n- 결제 항목: 파스텔골프클럽 60분 이용권 (평일 주간 혜택 70분)\n- 승인 금액: 42,000원\n- 승인 일시: 2026-08-23 09:10:00\n- 가맹점: 파스텔골프클럽`,
      receivedAt: "2026-08-23T09:10:00.000Z",
      isRead: false,
      isStarred: true,
    },
    {
      id: "naver-real-002",
      provider: "naver",
      accountEmail: NAVER_USER,
      senderName: "네이버 보안센터",
      senderEmail: "account_noreply@naver.com",
      subject: "[네이버] 외부 프로그램 애플리케이션 전용 비밀번호 연동 완료",
      snippet: `${NAVER_USER} 계정에 새로운 외부 메일 모듈 연동 접근이 승인되었습니다.`,
      body: `안녕하세요, ${NAVER_USER}님.\n\n회원님의 네이버 계정에 애플리케이션 전용 비밀번호를 통한 외부 서비스 연결이 성공적으로 등록되었습니다.\n\n- 연동 계정: ${NAVER_USER}\n- 서비스명: 종합 메일 모듈\n- 연동 일시: 2026-08-23 09:14:00\n\n본인이 설정한 것이 아니라면 즉시 보안 설정을 변경하세요.`,
      receivedAt: "2026-08-23T09:14:00.000Z",
      isRead: false,
      isStarred: false,
    },
    {
      id: "naver-real-003",
      provider: "naver",
      accountEmail: NAVER_USER,
      senderName: "엑스파트너스 POS지원팀",
      senderEmail: "support@xpartners.co.kr",
      subject: "[엑스파트너스] 8/22 파스텔골프클럽 일일 결제 정산 보고서",
      snippet: "8월 22일 포스 유료 결제 535건 카드/현금 정산 내역 첨부파일 안내입니다.",
      body: `수신: ${NAVER_USER}\n\n8월 22일 파스텔골프클럽 엑스파트너스 포스 유료 결제 정산 내역서입니다.\n\n- 유료 승인: 535건\n- 카드 매출액: 35,410,000원\n- 현금 매출액: 3,930,000원\n- 순 매출액: 38,553,000원\n\n첨부된 엑셀 정산 파일을 참조 바랍니다.`,
      receivedAt: "2026-08-22T18:00:00.000Z",
      isRead: true,
      isStarred: true,
    },
    {
      id: "naver-hist-004",
      provider: "naver",
      accountEmail: NAVER_USER,
      senderName: "네이버 메일팀",
      senderEmail: "mail_official@naver.com",
      subject: "[네이버 메일] POP3/IMAP 설정 변경이 성공적으로 완료되었습니다",
      snippet: `${NAVER_USER} 계정의 외부메일 읽기(IMAP/POP3) 원본 보관 옵션이 변경되었습니다.`,
      body: `안녕하세요, ${NAVER_USER}님.\n\n네이버 메일 환경설정에서 IMAP/POP3 연동 옵션이 성공적으로 변경 완료되었습니다.\n\n- 변경 일시: 2026년 8월 21일 10:15\n- 설정을 하지 않으셨다면 보안센터에서 암호를 변경하세요.`,
      receivedAt: "2026-08-21T10:15:00.000Z",
      isRead: true,
      isStarred: false,
    },
    {
      id: "naver-hist-005",
      provider: "naver",
      accountEmail: NAVER_USER,
      senderName: "네이버 개인정보 관리",
      senderEmail: "privacy_info@naver.com",
      subject: "[네이버] 개인정보 이용내역 관리 정기 안내 (2026년 8월)",
      snippet: "정보통신망법에 따른 네이버 개인정보 수집 및 활용 현황 정기 통지서입니다.",
      body: `안녕하세요, ${NAVER_USER} 회원님.\n\n네이버는 관련 법령에 따라 회원님의 개인정보 이용 내역을 매년 정기적으로 안내해 드리고 있습니다.\n\n- 회원 ID: ${NAVER_USER}\n- 수집 항목: 아이디, 이름, 휴대폰 번호, 이메일\n- 보유 및 이용 기간: 회원 탈퇴 시까지`,
      receivedAt: "2026-08-21T09:00:00.000Z",
      isRead: true,
      isStarred: false,
    },
    {
      id: "naver-hist-006",
      provider: "naver",
      accountEmail: NAVER_USER,
      senderName: "쿠팡 로켓배송",
      senderEmail: "shipment@coupang.com",
      subject: "[쿠팡] 주문하신 상품이 배송 완료되었습니다 (골프 양양 장갑 3팩)",
      snippet: `${NAVER_USER}님, 문 앞에 상품 작성이 완료되었습니다. 사진을 확인하세요.`,
      body: `안녕하세요, ${NAVER_USER}님.\n\n주문하신 상품이 지정하신 장소로 배송 완료되었습니다.\n\n- 주문 상품: [양손 세트] 프리미엄 골프장갑 3팩\n- 배송 장소: 문 앞\n- 배송 완료 일시: 2026-08-20 16:45`,
      receivedAt: "2026-08-20T16:45:00.000Z",
      isRead: true,
      isStarred: false,
    },
    {
      id: "naver-hist-007",
      provider: "naver",
      accountEmail: NAVER_USER,
      senderName: "KB국민카드",
      senderEmail: "kbcard_statement@kbstar.com",
      subject: "[KB국민카드] 8월 신용카드 이용대금 명세서 도착 안내",
      snippet: "8월 결제 예정금액 및 이용 세부 내역서 안내입니다.",
      body: `안녕하세요, ${NAVER_USER} 고객님.\n\n8월 KB국민카드 결제예정금액 명세서입니다.\n\n- 결제일: 2026년 8월 25일\n- 총 결제 예정액: 1,482,500원\n\n자세한 명세서는 보안 메일 첨부파일을 열어 확인해 주세요.`,
      receivedAt: "2026-08-18T09:20:00.000Z",
      isRead: true,
      isStarred: true,
    },
    {
      id: "naver-hist-008",
      provider: "naver",
      accountEmail: NAVER_USER,
      senderName: "네이버 클라우드",
      senderEmail: "noreply@navercloud.com",
      subject: "[Naver Cloud Platform] 8월 서비스 이용 약관 개정 사전 안내",
      snippet: "2026년 9월 1일부터 적용되는 네이버 클라우드 약관 개정 사항 안내입니다.",
      body: `안녕하세요, 네이버 클라우드 플랫폼입니다.\n\n2026년 9월 1일자로 서비스 약관 및 개인정보 처리방침이 일부 개정될 예정임을 안내해 드립니다.\n\n- 개정 대상: 데이터 보존 정책 및 데이터베이스 자동 백업 주기\n- 적용 일시: 2026년 9월 1일`,
      receivedAt: "2026-08-15T14:10:00.000Z",
      isRead: true,
      isStarred: false,
    },
  ];
}

export async function getGmailMails(): Promise<MailItem[]> {
  return [
    {
      id: "gmail-001",
      provider: "gmail",
      accountEmail: "zollove@gmail.com",
      senderName: "Vercel Deployment",
      senderEmail: "notifications@vercel.com",
      subject: "[Vercel] Deployment successful: work-board (main)",
      snippet: "Your project work-board was successfully deployed to production on Vercel.",
      body: "Deployment Complete!\n\nProject: work-board\nBranch: main\nURL: https://work-board.vercel.app\nStatus: Ready (Exit code 0)",
      receivedAt: "2026-08-23T08:50:00.000Z",
      isRead: false,
      isStarred: false,
    },
    {
      id: "gmail-002",
      provider: "gmail",
      accountEmail: "zollove@gmail.com",
      senderName: "Google Cloud Platform",
      senderEmail: "gcp-support@google.com",
      subject: "[Google Cloud] Infrastructure Uptime & Security Status Report",
      snippet: "Your Google Cloud Platform project resources operated with 99.99% uptime last week.",
      body: "Weekly Executive Summary\n\nProject ID: antigravity-workboard\nRegion: asia-northeast3 (Seoul)\nStatus: Healthy\nUptime: 99.99%",
      receivedAt: "2026-08-23T07:10:00.000Z",
      isRead: true,
      isStarred: true,
    },
    {
      id: "gmail-003",
      provider: "gmail",
      accountEmail: "zollove@gmail.com",
      senderName: "Supabase Team",
      senderEmail: "support@supabase.io",
      subject: "[Supabase] Database Connection Pooling & Pagination Optimization",
      snippet: "Your Supabase project limit extension for pastel_sessions table has been applied.",
      body: "Hello,\n\nWe have updated your database max rows per request settings.\nRange queries up to 99,999 records are now supported for your account.",
      receivedAt: "2026-08-21T18:20:00.000Z",
      isRead: true,
      isStarred: false,
    },
  ];
}
